pokemons-db:
  image: postgres:latest
  container_name: pokemons-db
  ports:
    - "5432"
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: root
    POSTGRES_DB: pokemons_database
  volumes:
    - pokemon-db:/var/lib/postgresql/data
volumes:
  pokemon-db:
